version: "3"
services:
  node_red:
    image: nodered/node-red-docker
    container_name: mynodered2
    ports:
    - "1880:1880"
    networks:
      - intranet2

  mongodb:
    image: mongo
    container_name: mongo2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=nodered
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
        - ../mongoDB_DATA:/data/db
    ports:
    - "2701:2701"
    networks:
      - intranet2


  mongo-express:
    image: mongo-express
    container_name: mongo_express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=wagno
      - ME_CONFIG_BASICAUTH_PASSWORD=user
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345
      - ME_CONFIG_MONGODB_SERVER=mongo2
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - intranet2

  find3:
    image: find3
    container_name: find3_server
    environment:
      - MQTT_ADMIN=ADMIN
      - MQTT_PASS=PASSWORD
      - MQTT_SERVER="localhost:1883"
      - MQTT_EXTERNAL='200.131.56.12'
      - MQTT_PORT=1884
    volumes:
        - ../find3_DATA:/data
    ports:
      - "1884:1883"
      - "8005:8003"
    networks:
      - intranet2

networks:
  intranet2:
    driver: bridge